### ISSUE TITLE
[STORY] Document the setup of NeuroDesk on AIS (e.g. CVFMS)

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#293]
### Metadata

Epic:
Feature:
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

Create documentation page on AIS developer website documenting how to set up CVMFS on k8s on NeuroDesk

### Acceptance Criteria

- [ ] 1. Webpage in Dev docs describing CVMFS setup
- [ ] 2. Another AIS team member checks the docs and see whether they can follow them (e.g. @fxusyd )

### Blocked by

- [ ]

**Comment by anzhao** [comment]
1. Install the CernVM-FS client. On Ubuntu, you can install it by executing the following commands:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/1094e063-7859-4f44-8a22-d48974fd0616)

2. Configure the CVMFS. For the basic config, run cvmfs_config setup. This ensures that the file /etc/auto.master.d/cvmfs.autofs exists containing /cvmfs /etc/auto.cvmfs and that the autofs service is running. Reload the autofs service in order to apply an updated configuration. Once done, create the keys and configure the neurodesk.ardc.edu.au as below:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/34db8df9-d3a5-4985-8281-4aab6427db33)

3. Test if the Neurodesk CVMFS repo is reachable or not (cvmfs_config stat -v neurodesk.ardc.edu.au).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/51866687-b6b5-458c-8722-18ddefd6f7c2)

**Comment by anzhao** [comment]
# Setup the CVMFS and NeuroDesk


## What is CVMFS

- CVMFS stands for CernVM File System, which provides a scalable, reliable and low-maintenance software distribution service. CVMFS is implemented as a POSIX read-only file system in user space (a FUSE module). All the files are hosted on standard web servers and mounted in universal namespace /cvmfs. You can think CVMFS as a contnent distribution network for software. It makes the centrally managed and updated software repositories avaibale acorss resources. Once you have access a sofeware via CVMFS, it will be cached locally, thus providing runtime performancve comparable to locally installed versions.

## How to install CVMFS

The CernVM-FS source code and binary packages are available from the [CernVM website](https://cernvm.cern.ch/portal/filesystem/downloads). As an example, on Ubuntu, you can install it by executing the following commands:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/6df75b83-deda-48d6-a6ef-59e3fbdacb22)

## configure Neurodesk hosted on CVMFS

- run "cvmfs_config setup" to do the initial setup and ensures that the file /etc/auto.master.d/cvmfs.autofs exists containing /cvmfs /etc/auto.cvmfs and that the autofs service is running. Reload the autofs service in order to apply an updated configuration. Once done, create the keys and configure the neurodesk.ardc.edu.au as below:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/1d89cba4-f68f-4d40-85a3-3a969d3247d4)

## Test the overal cvmfs configurations:
- First, test the overall cvmfs config setup by running "sudo cvmfs_config chksetup" as below:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/1076d5ed-c9bd-4e1a-86d5-fbebe859749c)

- Second, check if you can list the Neurodesk containers and modules:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/6633d464-838a-4ea7-9786-b04aea60ad6f)

- Third, check the speed and nearest Neurodesk cvmfs host:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/0d1d142d-f3f1-4027-aaa7-b35c84c77bb5)

## Setup the JupyterHub plugin:

- Before we are able to launch the NeuroDesk, we must make sure that the JupyterHub is able to communicate with our XNAT. One critial step is to figure out the correct JupyterHub API URL shown as below:


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/453200bb-f073-4a2f-a180-d4fe87a16cf3)

- In the meanwhile, remember to enable the Jupyter for the users.


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/8594b52d-e9a3-4c9e-ae64-ea77e1178a1c)

- In the Jupyter environment, please pick the Neurodesk Image you want to launch and in the following example, we pick the image "vnmd/neurodesktop:2024-01-12".


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/76026ba0-d06d-4fd5-8126-cbcfecb168e8)

- You can setup additional environment by click the above "New Jupyter Environment" button and the following window will pop up.


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/0e8dc1c7-8217-4413-94b4-1c668432d01a)

- Allocate hardware to the jupyter users.
  - You can create Hardware configurations that define the hardware resources that will be allocated to the single-user server when it is launched. Additional configuration options (such as cpu and memory limits) can be specified


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/efd97b47-e383-421b-8427-4bddd49d938e)

## Launch the Neurodesk:
After you have setup all the above steps, you can launch the Neurodesk by visiting any XNAT project and click the "start jupyter" in the right side as below. Remember to select the Neurodesk image and desired hardware size.

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/874dd5a5-a9bd-4df5-8cb5-d9353e7a258a)

- Once you click the "start jupyter" button, a few things such as "JupyterHub is spawning container" are happened as backend shown below:


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/076a864c-7669-42ac-b718-3ce6d7aa858a)

## Neurodesk launched in Jupyter

After you click the Jupyter URL, you will be bring to JupyterLab as below:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/f2b44fff-f57a-4ab9-bdba-76c83a4d2f76)

If you click the Neurodesk icon, you will be coming to the Neurodesk desktop environment as below:


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/8696b04d-74dc-4352-a537-0163929059f8)



![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/d42034b3-2622-420b-9d89-8da45d599823)



![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/c90bafcc-6517-4bb1-86d7-957752face1d)

**Comment by tclose** [comment]
Just needs to be put up on AIS docs
